### ISSUE TITLE
What about adding a "Data Visualization" Category?

### ISSUE THREAD

**Issue by phonicmouse** [ramnes/awesome-mongodb#21]
I think it would be very useful ;)

**Comment by ramnes** [comment]
Yep. :+1: 

I've reworked a bit categories so that there's a web tools category that's not only about clients but also data visualization. HumongouS was already there, but not properly worded so I modified its description.

I also added Compass in that category, which is the (or "one of the"?) MongoDB Inc. data visualization product.

If we get more "data-visualization-centric" tools, I'll consider adding a completely dedicated category and removing them from that new "Web" category, but for now I feel it's good enough.

I remain open to suggestions, don't hesitate to submit a pull request!

Thanks.

**Comment by phonicmouse** [comment]
I have a couple of data visualization tools to add but they are not only for mongodb (metabase and redash), can I add them anyway?

**Comment by ramnes** [comment]
I think we would get out of scope, sorry.

**Comment by phonicmouse** [comment]
No problem, if i'll find out something else i'll let you know ;)
