### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by jsoendermann** [ramnes/awesome-mongodb#24]
Hi,

Thanks for taking the effort to make this repo.

I wrote [a style guide](https://github.com/jsoendermann/MongoStyleGuide) for MongoDB data modeling, would there be any interest in adding it to this repo?

**Comment by ramnes** [comment]
Hi @jsoendermann,

Thanks for your proposal!

Your guide is indeed interesting and would definitely have its place here, but I wouldn't include it yet because it still seems to be work in progress and also seems to have very low traction for now. That second point is particularly relevant here because, as you describe it, it's "opinionated" and I don't want to take the responsibility of that opinion unless it's backed by the community.

I'm closing this issue but feel free to open a PR later when you'll think it's mature enough. :+1:

**Comment by jsoendermann** [comment]
Hi again,

I posted the style guide on reddit last week and got some very positive feedback. It's now sitting at 44 stars, would that be sufficient traction to warrant inclusion in awesome-mongodb?

Thanks for your consideration.

**Comment by ramnes** [comment]
The Todo section still tickles me. :wink: 

Finish what you had in mind and we'll include it here.

**Comment by jsoendermann** [comment]
The Todo section includes things that at this point I'm not sure how to handle best, it's there to invite proposals from people who have thought more about them.

**Comment by ramnes** [comment]
I understand. Still, I'd prefer to include your guide without this section. Either find the relevant people to help you with this, or learn from others (IRC, [documentation](https://docs.mongodb.com/manual/core/data-model-design/), [books](http://shop.oreilly.com/product/0636920027041.do), [videos](https://www.youtube.com/watch?v=csKBT8zkRf0), etc.)

**Comment by jsoendermann** [comment]
I see. Perhaps at a later point then.
